# Generated by Django 5.0.4 on 2024-04-27 14:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("googlemap", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticOverlayPointField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Use map widget to point the location", srid=4326
                    ),
                ),
                (
                    "location_optional",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Static Overlay PointField",
                "verbose_name_plural": "Static Overlay PointField",
            },
        ),
        migrations.CreateModel(
            name="StaticPointField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Use map widget to point the location", srid=4326
                    ),
                ),
                (
                    "location_optional",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Static PointField",
                "verbose_name_plural": "Static PointField",
            },
        ),
    ]
