# Generated by Django 5.0.4 on 2024-04-27 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("googlemap", "0002_staticoverlaypointfield_staticpointfield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StaticOverlayPointField",
        ),
        migrations.DeleteModel(
            name="StaticPointField",
        ),
    ]
