# Generated by Django 5.0.6 on 2024-06-21 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("googlemap", "0003_delete_staticoverlaypointfield_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticPointField",
            fields=[],
            options={
                "verbose_name": "Static PointField Widget",
                "verbose_name_plural": "Static PointField Widget",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("googlemap.interactivepointfield",),
        ),
        migrations.AlterModelOptions(
            name="interactiveinlinepointfield",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="interactivepointfield",
            options={
                "verbose_name": "Interactive PointField Widget",
                "verbose_name_plural": "Interactive PointField Widget",
            },
        ),
    ]
