# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 01:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='PointFieldInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.PointField')),
            ],
        ),
    ]
