# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-05 16:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
        ),
        migrations.AlterField(
            model_name='district',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='To generate the map for your location', srid=4326),
        ),
    ]
