# Generated by Django 5.0.6 on 2024-06-21 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leaflet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interactivepointfield",
            options={
                "verbose_name": "Interactive PointField Widget",
                "verbose_name_plural": "Interactive PointField Widgets",
            },
        ),
    ]
