# Generated by Django 5.2.12 on 2026-06-22 15:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaflet", "0002_alter_interactivepointfield_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractivePolygonField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        help_text="Use map widget to draw the area", srid=4326
                    ),
                ),
                (
                    "area_optional",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Interactive PolygonField Widget",
                "verbose_name_plural": "Interactive PolygonField Widgets",
            },
        ),
    ]
